---
all:
  children:
    windows:
      hosts:
        client:
          ansible_host: 10.10.2.6
          ansible_user: labadmin
          ansible_password: "{{ vault_admin_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
          mssql_instance_name: "MSSQLSERVER"
          mssql_sa_password: "{{ vault_mssql_sa_password }}"
          mssql_port: 1433
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
    
    linux:
      hosts:
        linux:
          ansible_host: 10.10.2.5
          ansible_user: labadmin
          ansible_password: "{{ vault_admin_password }}"
          ansible_connection: ssh
          ansible_port: 22
          ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no'
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: "{{ vault_admin_password }}"
          apache_port: 80
          nginx_port: 8080
      vars:
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no'

