---
collections:
  - name: ansible.windows
    version: ">=1.14.0"
  - name: community.windows
    version: ">=1.14.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=7.0.0"

